# Generated by Django 5.2.8 on 2025-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
