# Generated by Django 5.2.8 on 2025-11-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_url_payment_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_url",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="session_id",
        ),
    ]
