# Generated by Django 5.2.8 on 2025-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_payment_payment_url_remove_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
