# Generated by Django 5.2.8 on 2025-11-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Цена курса"),
        ),
    ]
