# Generated by Django 5.2.8 on 2025-11-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_lesson_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="price",
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Цена курса"),
        ),
    ]
