# Generated by Django 5.2.8 on 2025-11-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_remove_lesson_price_course_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
    ]
